In [ ]:
import pandas as pd
import numpy as np

In [ ]:
series=pd.Series([1,3,5,6,8])
print("1.Pandas Series:")
print(series)

1.Pandas Series:
0    1
1    3
2    5
3    6
4    8
dtype: int64


In [ ]:


data={
    "Country":["Brazil","Russia","India","China","South Africa"],
    "Capital":["Brasilia","Moscow","New Delhi","Beijing","Pretoria"],
    "Area":[8515767,17098242,3287263,9596961,1221037],
    "Population": [216,144,1428,1412,60]
}

brics=pd.DataFrame(
    data,
    index=["BR","RU","IN","CH","SA"]
)

print("2.BRICS DataFrame:")
print(brics)


2.BRICS DataFrame:
         Country    Capital      Area  Population
BR        Brazil   Brasilia   8515767         216
RU        Russia     Moscow  17098242         144
IN         India  New Delhi   3287263        1428
CH         China    Beijing   9596961        1412
SA  South Africa   Pretoria   1221037          60


In [ ]:
cars=pd.read_csv("/content/cars1 - cars1.csv")
print("\n3.Complete Dataset:")
print(cars)
print("\nFirst four records:")
print(cars.head(4))
print("\nFifth and sixth records:")
print(cars.iloc[4:6])
print("\nThird row using iloc:")
print(cars.iloc[2])



3.Complete Dataset:
      mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0    18.0          8           307        130    3504          12.0     70   
1    15.0          8           350        165    3693          11.5     70   
2    18.0          8           318        150    3436          11.0     70   
3    16.0          8           304        150    3433          12.0     70   
4    17.0          8           302        140    3449          10.5     70   
..    ...        ...           ...        ...     ...           ...    ...   
193  24.0          6           200         81    3012          17.6     76   
194  22.5          6           232         90    3085          17.6     76   
195  29.0          4            85         52    2035          22.2     76   
196  24.5          4            98         60    2164          22.1     76   
197  29.0          4            90         70    1937          14.2     76   

     origin                        car  
0

In [ ]:
student_data={
    "Name":["Anu","Rahul","John","Meera","Arun"],
    "Gender":["Female","Male","Male","Female","Male"],
    "Age":[20,21,22,20,23]
    }
students=pd.DataFrame(student_data)
print("\n4.Complete Student DataFrame:")
print(students)
print("\nFirst two rows:")
print(students.iloc[:2])
print("\nFrom third row onwards:")
print(students.iloc[2:])


4.Complete Student DataFrame:
    Name  Gender  Age
0    Anu  Female   20
1  Rahul    Male   21
2   John    Male   22
3  Meera  Female   20
4   Arun    Male   23

First two rows:
    Name  Gender  Age
0    Anu  Female   20
1  Rahul    Male   21

From third row onwards:
    Name  Gender  Age
2   John    Male   22
3  Meera  Female   20
4   Arun    Male   23


In [ ]:
random_series=pd.Series(np.random.rand(4))
print("\n5. Random Number Series:")
print(random_series)
print("\nValues stored in the Series:")
print(random_series.values)
print("\nFirst two elements using head():")
print(random_series.head(2))
print("\nLast three elements using tail():")
print(random_series.tail(3))


5. Random Number Series:
0    0.241292
1    0.494586
2    0.243356
3    0.868099
dtype: float64

Values stored in the Series:
[0.24129185 0.49458646 0.2433564  0.86809879]

First two elements using head():
0    0.241292
1    0.494586
dtype: float64

Last three elements using tail():
1    0.494586
2    0.243356
3    0.868099
dtype: float64


In [ ]:
employee_data={
    "Name":["Alice","Bob","Charlie","David"],
    "Age":[25,30,28,35],
    "Rating":[4.5,3.8,4.2,4.7]
    }
df=pd.DataFrame(employee_data)
print("\n6. Employee DataFrame:")
print(df)
print("\nTranspose of DataFrame:")
print(df.T)
print("\nRow and Column Labels using axes:")
print(df.axes)
print("\nData type of each column:")
print(df.dtypes)
print("\nIs the DataFrame empty?")
print(df.empty)
print("\nNumber of dimensions:")
print(df.ndim)
print("\nShape of the DataFrame:")
print(df.shape)
print("\nTotal number of elements:")
print(df.size)
print("\nValues stored in the DataFrame:")
print(df.values)
print("\nNumber of missing values in each column:")
print(df.isnull().sum())


6. Employee DataFrame:
      Name  Age  Rating
0    Alice   25     4.5
1      Bob   30     3.8
2  Charlie   28     4.2
3    David   35     4.7

Transpose of DataFrame:
            0    1        2      3
Name    Alice  Bob  Charlie  David
Age        25   30       28     35
Rating    4.5  3.8      4.2    4.7

Row and Column Labels using axes:
[RangeIndex(start=0, stop=4, step=1), Index(['Name', 'Age', 'Rating'], dtype='object')]

Data type of each column:
Name       object
Age         int64
Rating    float64
dtype: object

Is the DataFrame empty?
False

Number of dimensions:
2

Shape of the DataFrame:
(4, 3)

Total number of elements:
12

Values stored in the DataFrame:
[['Alice' 25 4.5]
 ['Bob' 30 3.8]
 ['Charlie' 28 4.2]
 ['David' 35 4.7]]

Number of missing values in each column:
Name      0
Age       0
Rating    0
dtype: int64


6)Write a Python program to implement k-NN classification using the Iris dataset. Perform the
following steps:
1. Load the dataset using Pandas.
2. Separate the features and target variable.
3. Split the dataset into 80% training and 20% testing data.
4. Apply StandardScaler for feature scaling.
5. Train a k-NN classifier with k = 5.
6. Predict the classes of the test data.
7. Display the confusion matrix, classification report, and accuracy.





In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [ ]:

dataset=pd.read_csv("/content/Iris - Iris.csv")
print(dataset.head())


   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [ ]:
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:, 5].values


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=0)

In [ ]:
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)


In [ ]:
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)


KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_test)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("Classification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
Accuracy: 1.0
Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         6

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

